apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: fake
spec:
  provider:
    fake:
      data:
        - key: "cdp-s3"
          valueMap:
            CDP_ACCESS_KEY_ID: aaa
            CDP_PRIVATE_KEY: bbb